# Generated by Django 4.2.11 on 2024-06-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='email',
        ),
    ]
