# Generated by Django 4.2.11 on 2024-06-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_postcomment_name_postcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
